/*******************************************************************************
HELPER PROGRAMS FOR projectinit v2.1.0
================================================================================
These programs should be appended to projectinit_v2_enhanced.ado
or loaded separately
*******************************************************************************/

********************************************************************************
* Elite .gitignore (DevOps Grade)
********************************************************************************
program define projectinit_gitignore_elite
    syntax, PATH(string) LAtex(string)

    file open gitfile using `"`path'/.gitignore"', write replace

    file write gitfile "# =============================================================================" _n
    file write gitfile "# .gitignore - Elite Research Project (J-PAL/DIME/AEA Standard)" _n
    file write gitfile "# Generated by projectinit v2.1.0" _n
    file write gitfile "# =============================================================================" _n
    file write gitfile "" _n
    file write gitfile "# CRITICAL: Raw microdata (NEVER commit sensitive data)" _n
    file write gitfile "01_Data/Raw/" _n
    file write gitfile "01_Data/De-identified/*.dta" _n
    file write gitfile "*.dta" _n
    file write gitfile "*.csv" _n
    file write gitfile "*.xlsx" _n
    file write gitfile "*.xls" _n
    file write gitfile "*.sav" _n
    file write gitfile "*.por" _n
    file write gitfile "" _n
    file write gitfile "# Stata temporary and log files" _n
    file write gitfile "*.smcl" _n
    file write gitfile "*.log" _n
    file write gitfile "*.dta~" _n
    file write gitfile "*.do~" _n
    file write gitfile "*.gph" _n
    file write gitfile "*.stpr" _n
    file write gitfile "" _n
    file write gitfile "# Temporary directories" _n
    file write gitfile "temp/" _n
    file write gitfile "tmp/" _n
    file write gitfile "*.tmp" _n
    file write gitfile "" _n
    file write gitfile "# Logs (keep structure, ignore content)" _n
    file write gitfile "03_Outputs/Logs/*.log" _n
    file write gitfile "03_Outputs/Logs/*.smcl" _n
    file write gitfile "" _n

    if "`latex'" != "none" {
        file write gitfile "# LaTeX compilation artifacts" _n
        file write gitfile "*.aux" _n
        file write gitfile "*.out" _n
        file write gitfile "*.bbl" _n
        file write gitfile "*.blg" _n
        file write gitfile "*.synctex.gz" _n
        file write gitfile "*.fdb_latexmk" _n
        file write gitfile "*.fls" _n
        file write gitfile "*.toc" _n
        file write gitfile "*.lof" _n
        file write gitfile "*.lot" _n
        file write gitfile "*.nav" _n
        file write gitfile "*.snm" _n
        file write gitfile "*.vrb" _n
        file write gitfile "*.bcf" _n
        file write gitfile "*.run.xml" _n
        file write gitfile "*.bak" _n
        file write gitfile "*.spl" _n
        file write gitfile "" _n
    }

    file write gitfile "# OS-specific files" _n
    file write gitfile ".DS_Store" _n
    file write gitfile "._*" _n
    file write gitfile "Thumbs.db" _n
    file write gitfile "ehthumbs.db" _n
    file write gitfile "Desktop.ini" _n
    file write gitfile "\$RECYCLE.BIN/" _n
    file write gitfile ".Spotlight-V100" _n
    file write gitfile ".Trashes" _n
    file write gitfile "" _n
    file write gitfile "# IDE and editor files" _n
    file write gitfile ".vscode/" _n
    file write gitfile ".idea/" _n
    file write gitfile "*.sublime-project" _n
    file write gitfile "*.sublime-workspace" _n
    file write gitfile "*~" _n
    file write gitfile "" _n
    file write gitfile "# =============================================================================" _n
    file write gitfile "# EXCEPTIONS (Force include these critical outputs)" _n
    file write gitfile "# =============================================================================" _n
    file write gitfile "" _n
    file write gitfile "# Keep final tables and figures for replication" _n
    file write gitfile "!03_Outputs/Tables/*.tex" _n
    file write gitfile "!03_Outputs/Tables/*.csv" _n
    file write gitfile "!03_Outputs/Figures/*.pdf" _n
    file write gitfile "!03_Outputs/Figures/*.png" _n
    file write gitfile "!03_Outputs/Figures/*.eps" _n
    file write gitfile "" _n
    file write gitfile "# Keep replication package data (if de-identified)" _n
    file write gitfile "!06_Replication/data/*.dta" _n
    file write gitfile "" _n
    file write gitfile "# Keep codebooks and documentation" _n
    file write gitfile "!05_Doc/**/*.pdf" _n
    file write gitfile "!05_Doc/**/*.md" _n
    file write gitfile "" _n
    file write gitfile "# End of .gitignore" _n

    file close gitfile

    di as result "  ✓ .gitignore (Elite)"
end

********************************************************************************
* AEA-Compliant README.md
********************************************************************************
program define projectinit_readme_aea
    syntax, PATH(string) PROJname(string) LAng(string) AUthor(string) ///
        Email(string) LAtex(string) GIThub(string)

    file open readmefile using `"`path'/README.md"', write replace

    if "`lang'" == "en" {
        file write readmefile "# `projname'" _n
        file write readmefile "" _n
        file write readmefile "> **Research Project following J-PAL, DIME, and AEA Standards**" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Project Information" _n
        file write readmefile "" _n
        file write readmefile "- **Principal Investigator**: `author'" _n
        file write readmefile "- **Email**: `email'" _n
        file write readmefile "- **Created**: `c(current_date)'" _n
        file write readmefile "- **Last Modified**: `c(current_date)'" _n
        file write readmefile "- **Software**: Stata `c(stata_version)' or higher" _n
        file write readmefile "- **Generated by**: projectinit v2.1.0" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Overview" _n
        file write readmefile "" _n
        file write readmefile "[Provide a brief description of your research project]" _n
        file write readmefile "" _n
        file write readmefile "This project adheres to:" _n
        file write readmefile "- **J-PAL (MIT)** reproducibility guidelines" _n
        file write readmefile "- **DIME (World Bank)** best practices" _n
        file write readmefile "- **AEA Data Editor** requirements" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Data Availability Statement" _n
        file write readmefile "" _n
        file write readmefile "### Primary Data Sources" _n
        file write readmefile "" _n
        file write readmefile "[Describe your data sources following AEA guidelines]" _n
        file write readmefile "" _n
        file write readmefile "**Example for Chilean/Peruvian microdata:**" _n
        file write readmefile "" _n
        file write readmefile "- **CASEN (Chile)**: National Socioeconomic Characterization Survey" _n
        file write readmefile "  - Source: Ministry of Social Development and Family, Chile" _n
        file write readmefile "  - Access: http://observatorio.ministeriodesarrollosocial.gob.cl/" _n
        file write readmefile "  - Restriction: Publicly available" _n
        file write readmefile "" _n
        file write readmefile "- **ENAHO (Peru)**: National Household Survey" _n
        file write readmefile "  - Source: INEI (National Institute of Statistics, Peru)" _n
        file write readmefile "  - Access: http://iinei.inei.gob.pe/microdatos/" _n
        file write readmefile "  - Restriction: Publicly available with registration" _n
        file write readmefile "" _n
        file write readmefile "### Data Access" _n
        file write readmefile "" _n
        file write readmefile "- **Confidentiality**: [Describe any confidentiality restrictions]" _n
        file write readmefile "- **IRB Approval**: [Provide IRB information if applicable]" _n
        file write readmefile "- **Data Sharing**: [Specify what data will be shared for replication]" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Project Structure" _n
        file write readmefile "" _n
        file write readmefile "```" _n
        file write readmefile "`projname'/" _n
        file write readmefile "│" _n
        file write readmefile "├── run.do                    # Master execution script (START HERE)" _n
        file write readmefile "├── README.md                 # This file" _n
        file write readmefile "├── .gitignore                # Git configuration" _n
        file write readmefile "│" _n
        file write readmefile "├── 01_Data/                  # Data (J-PAL/DIME standard)" _n
        file write readmefile "│   ├── Raw/                  # Original data (NEVER modified)" _n
        file write readmefile "│   ├── De-identified/        # Anonymized data" _n
        file write readmefile "│   ├── Intermediate/         # Processed data" _n
        file write readmefile "│   └── Final/                # Analysis-ready data" _n
        file write readmefile "│" _n
        file write readmefile "├── 02_Scripts/               # All analysis code (NBER standard)" _n
        file write readmefile "│   ├── Ados/                 # Project-specific ado files" _n
        file write readmefile "│   ├── Data_Preparation/     # Data cleaning and construction" _n
        file write readmefile "│   ├── Analysis/             # Statistical analysis" _n
        file write readmefile "│   └── Validation/           # Validation and robustness" _n
        file write readmefile "│" _n
        file write readmefile "├── 03_Outputs/               # Generated outputs (AEA standard)" _n
        file write readmefile "│   ├── Tables/               # Publication-ready tables" _n
        file write readmefile "│   ├── Figures/              # Publication-ready figures" _n
        file write readmefile "│   ├── Logs/                 # Execution logs" _n
        file write readmefile "│   └── Raw_Outputs/          # Intermediate outputs" _n
        file write readmefile "│" _n
    }
    else {
        file write readmefile "# `projname'" _n
        file write readmefile "" _n
        file write readmefile "> **Proyecto de Investigación siguiendo estándares J-PAL, DIME y AEA**" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Información del Proyecto" _n
        file write readmefile "" _n
        file write readmefile "- **Investigador Principal**: `author'" _n
        file write readmefile "- **Email**: `email'" _n
        file write readmefile "- **Creado**: `c(current_date)'" _n
        file write readmefile "- **Última Modificación**: `c(current_date)'" _n
        file write readmefile "- **Software**: Stata `c(stata_version)' o superior" _n
        file write readmefile "- **Generado por**: projectinit v2.1.0" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Descripción" _n
        file write readmefile "" _n
        file write readmefile "[Provea una breve descripción de su proyecto de investigación]" _n
        file write readmefile "" _n
        file write readmefile "Este proyecto cumple con:" _n
        file write readmefile "- Guías de reproducibilidad de **J-PAL (MIT)**" _n
        file write readmefile "- Mejores prácticas de **DIME (Banco Mundial)**" _n
        file write readmefile "- Requerimientos del **AEA Data Editor**" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Declaración de Disponibilidad de Datos" _n
        file write readmefile "" _n
        file write readmefile "### Fuentes de Datos Primarias" _n
        file write readmefile "" _n
        file write readmefile "[Describa sus fuentes de datos siguiendo las guías de AEA]" _n
        file write readmefile "" _n
        file write readmefile "**Ejemplo para microdatos chilenos/peruanos:**" _n
        file write readmefile "" _n
        file write readmefile "- **CASEN (Chile)**: Encuesta de Caracterización Socioeconómica Nacional" _n
        file write readmefile "  - Fuente: Ministerio de Desarrollo Social y Familia, Chile" _n
        file write readmefile "  - Acceso: http://observatorio.ministeriodesarrollosocial.gob.cl/" _n
        file write readmefile "  - Restricción: Disponible públicamente" _n
        file write readmefile "" _n
        file write readmefile "- **ENAHO (Perú)**: Encuesta Nacional de Hogares" _n
        file write readmefile "  - Fuente: INEI (Instituto Nacional de Estadística, Perú)" _n
        file write readmefile "  - Acceso: http://iinei.inei.gob.pe/microdatos/" _n
        file write readmefile "  - Restricción: Disponible con registro" _n
        file write readmefile "" _n
        file write readmefile "---" _n
        file write readmefile "" _n
        file write readmefile "## Estructura del Proyecto" _n
        file write readmefile "" _n
        file write readmefile "```" _n
        file write readmefile "`projname'/" _n
        file write readmefile "│" _n
        file write readmefile "├── run.do                    # Script de ejecución maestro (COMENZAR AQUÍ)" _n
        file write readmefile "├── README.md                 # Este archivo" _n
        file write readmefile "├── .gitignore                # Configuración Git" _n
        file write readmefile "│" _n
        file write readmefile "├── 01_Data/                  # Datos (estándar J-PAL/DIME)" _n
        file write readmefile "│   ├── Raw/                  # Datos originales (NUNCA modificar)" _n
        file write readmefile "│   ├── De-identified/        # Datos anonimizados" _n
        file write readmefile "│   ├── Intermediate/         # Datos procesados" _n
        file write readmefile "│   └── Final/                # Datos listos para análisis" _n
        file write readmefile "│" _n
        file write readmefile "├── 02_Scripts/               # Todo el código de análisis" _n
        file write readmefile "│   ├── Ados/                 # Comandos específicos del proyecto" _n
        file write readmefile "│   ├── Data_Preparation/     # Limpieza y construcción de datos" _n
        file write readmefile "│   ├── Analysis/             # Análisis estadístico" _n
        file write readmefile "│   └── Validation/           # Validación y robustez" _n
        file write readmefile "│" _n
        file write readmefile "├── 03_Outputs/               # Resultados generados" _n
        file write readmefile "│   ├── Tables/               # Tablas para publicación" _n
        file write readmefile "│   ├── Figures/              # Figuras para publicación" _n
        file write readmefile "│   ├── Logs/                 # Logs de ejecución" _n
        file write readmefile "│   └── Raw_Outputs/          # Resultados intermedios" _n
        file write readmefile "│" _n
    }

    if "`latex'" != "none" {
        file write readmefile "├── 04_Writing/               # Manuscript LaTeX" _n
        file write readmefile "│   ├── main.tex              # Main document" _n
        file write readmefile "│   ├── sections/             # Paper sections" _n
        file write readmefile "│   └── results_macros.tex    # Auto-generated from Stata" _n
        file write readmefile "│" _n
    }

    file write readmefile "├── 05_Doc/                   # Documentation" _n
    file write readmefile "│   ├── Codebooks/            # Data dictionaries" _n
    file write readmefile "│   ├── Questionnaires/       # Survey instruments" _n
    file write readmefile "│   └── IRB/                  # Ethics approvals" _n
    file write readmefile "```" _n
    file write readmefile "" _n
    file write readmefile "---" _n
    file write readmefile "" _n

    if "`lang'" == "en" {
        file write readmefile "## Replication Instructions" _n
        file write readmefile "" _n
        file write readmefile "### Prerequisites" _n
        file write readmefile "" _n
        file write readmefile "1. **Software**: Stata `c(stata_version)' or higher" _n
        file write readmefile "2. **Packages**: Automatically installed by `run.do`" _n
        file write readmefile "3. **Data**: [Specify how to obtain data]" _n
        file write readmefile "4. **Hardware**: Minimum 8GB RAM recommended" _n
        file write readmefile "5. **Runtime**: Approximately [X] hours on standard machine" _n
        file write readmefile "" _n
        file write readmefile "### Step-by-Step Replication" _n
        file write readmefile "" _n
        file write readmefile "1. **Clone or download this repository**" _n
        file write readmefile "   ```bash" _n
        file write readmefile "   git clone https://github.com/username/`projname'.git" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "2. **Place raw data** in `01_Data/Raw/`" _n
        file write readmefile "" _n
        file write readmefile "3. **Navigate to project directory** in Stata" _n
        file write readmefile "   ```stata" _n
        file write readmefile "   cd \"path/to/`projname'\"" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "4. **Execute master script**" _n
        file write readmefile "   ```stata" _n
        file write readmefile "   do run.do" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "5. **Check outputs**" _n
        file write readmefile "   - Tables: `03_Outputs/Tables/`" _n
        file write readmefile "   - Figures: `03_Outputs/Figures/`" _n
        file write readmefile "   - Logs: `03_Outputs/Logs/`" _n
        file write readmefile "" _n
        file write readmefile "### Troubleshooting" _n
        file write readmefile "" _n
        file write readmefile "- **Memory errors**: Increase `set max_memory` in run.do" _n
        file write readmefile "- **Package errors**: Install manually via `ssc install [package]`" _n
        file write readmefile "- **Path errors**: Ensure you're in the project directory" _n
        file write readmefile "" _n
    }
    else {
        file write readmefile "## Instrucciones de Replicación" _n
        file write readmefile "" _n
        file write readmefile "### Requisitos Previos" _n
        file write readmefile "" _n
        file write readmefile "1. **Software**: Stata `c(stata_version)' o superior" _n
        file write readmefile "2. **Paquetes**: Instalados automáticamente por `run.do`" _n
        file write readmefile "3. **Datos**: [Especificar cómo obtener los datos]" _n
        file write readmefile "4. **Hardware**: Mínimo 8GB RAM recomendado" _n
        file write readmefile "5. **Tiempo de ejecución**: Aproximadamente [X] horas" _n
        file write readmefile "" _n
        file write readmefile "### Pasos para Replicar" _n
        file write readmefile "" _n
        file write readmefile "1. **Clonar o descargar este repositorio**" _n
        file write readmefile "   ```bash" _n
        file write readmefile "   git clone https://github.com/usuario/`projname'.git" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "2. **Colocar datos crudos** en `01_Data/Raw/`" _n
        file write readmefile "" _n
        file write readmefile "3. **Navegar al directorio del proyecto** en Stata" _n
        file write readmefile "   ```stata" _n
        file write readmefile "   cd \"ruta/a/`projname'\"" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "4. **Ejecutar script maestro**" _n
        file write readmefile "   ```stata" _n
        file write readmefile "   do run.do" _n
        file write readmefile "   ```" _n
        file write readmefile "" _n
        file write readmefile "5. **Verificar resultados**" _n
        file write readmefile "   - Tablas: `03_Outputs/Tables/`" _n
        file write readmefile "   - Figuras: `03_Outputs/Figures/`" _n
        file write readmefile "   - Logs: `03_Outputs/Logs/`" _n
        file write readmefile "" _n
    }

    file write readmefile "---" _n
    file write readmefile "" _n
    file write readmefile "## Citation" _n
    file write readmefile "" _n
    file write readmefile "If you use this code or data, please cite:" _n
    file write readmefile "" _n
    file write readmefile "```" _n
    file write readmefile "`author' (`c(current_year)'). \"`projname'\"." _n
    file write readmefile "[Journal/Repository information]" _n
    file write readmefile "```" _n
    file write readmefile "" _n
    file write readmefile "---" _n
    file write readmefile "" _n
    file write readmefile "## License" _n
    file write readmefile "" _n
    file write readmefile "MIT License - see LICENSE file for details" _n
    file write readmefile "" _n
    file write readmefile "---" _n
    file write readmefile "" _n
    file write readmefile "## Contact" _n
    file write readmefile "" _n
    file write readmefile "- **Author**: `author'" _n
    file write readmefile "- **Email**: `email'" _n
    if "`github'" != "none" {
        file write readmefile "- **Repository**: https://github.com/username/`projname'" _n
    }
    file write readmefile "" _n
    file write readmefile "---" _n
    file write readmefile "" _n
    file write readmefile "*Generated by projectinit v2.1.0 - Professional Research Infrastructure*" _n

    file close readmefile

    di as result "  ✓ README.md (AEA-compliant)"
end

* Additional helper programs would continue here...
* Due to length constraints, key programs are shown above
* Complete version would include: latex_enhanced, scripts_jpal,
* github_enhanced, replication_aea

* End of helper programs
